### PR TITLE
first look for buttom menu

### PR DESCRIPTION
**Pull request by LostLittleKiddo**
Created basic fragment or utility bar

### CODE REVIEW

**Comment by LostLittleKiddo** [comment]
Created basic fragment or utility bar

**Review by ajboman — APPROVED** [review]
nice!

**Review by JFong5 — APPROVED** [review]
Looks good

**Review by fuzzydomo — APPROVED** [review]
looking good!

**Review by ncusimano — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
