### PR TITLE
Reset App to Include Resources Folder

### PR DESCRIPTION
**Pull request by ncusimano**
Resource folder and default build was missing from empty application. Made a fresh start of the project to add a default empty layout and the associated default infill for a new project so we aren't starting from scratch.

### CODE REVIEW

**Review by LostLittleKiddo — APPROVED** [review]
looks good

**Review by JFong5 — COMMENTED** [review]
DO IT

**Review by JFong5 — APPROVED** [review]

**Review by fuzzydomo — APPROVED** [review]
This is a smart idea

**Comment by ajboman** [comment]
Nice

**Review by ajboman — APPROVED** [review]
:+1:

**Review by minhalo113 — APPROVED** [review]
yes

**Pull request merged**
